<?php
declare(strict_types=1);

/** @var \WebGrip\ExampleModule\Block\Dummy $block */

/** @var \WebGrip\ExampleModule\ViewModels\MagewireViewModel $dummy */
//$dummy = $block->getData('webgrip.examplemodule.dummy'); // Same as:
$dummy = $block->getDummyViewModel();

//$product = $dummy->getProductById((int)$block->getData('product_id')); // Same as:

/** @var \Magento\Catalog\Model\Product $product */
$product = $dummy->getProductById((int)$block->getProductId());

$upsellProducts = $product->getUpSellProductCollection()->getItems();
?>
<div>
    <span>Product name: </span><span><?= $product->getName() ?></span>

    <div>Product ID: <?= $product->getId(); ?> </div>
    <div>Upsellers: <?= count($upsellProducts); ?> </div>
    <?php foreach ($upsellProducts as $upsellProduct): ?>
        <div>
            <span>Upsell product name: </span><span><?= $upsellProduct->getName() ?></span>
        </div>
    <?php endforeach; ?>

    Einde upsellers
</div>
